log_dir: "/micklem/data/download_logs"
data_dir: "/micklem/data/ecolimine"

default_sources:
  - "AffyProbes"
  - "BioGRID"
  - "EnsemblCompara"
  - "FlyBaseFasta"
  - "FlyBaseOrthologues"
  - "FlyOntologies"
  - "GOAnnotation"
  - "IntAct"
  - "IntactVocabulary"
  - "InterPro"
  - "InterProGO"
  - "MGIIdentifiers"
  - "NCBIGene"
  - "PDB"
  - "PubMed"
  - "Reactome"
  - "RedFly"
  - "RNAiScreens"
  - "UniProt"
  - "WormbaseRNAi"
  - "WormIdentifiers"

UniProt:
    organisms:
        - 83333
    excluded_organisms:
        - 10091
        - 10092
        - 35531
        - 39442
        - 46244
        - 57486
        - 63221
        - 116058
        - 180454
        - 377270
        - 377271
        - 377586
        - 377587
        - 943925
        - 943926
        - 595496
        - 316385
        

