log_dir: "/micklem/data/plantmine"
data_dir: "/micklem/data/plantmine"

default_sources:
  - "UniProt"

UniProt:
    organisms:
        - 3702
    excluded_organisms:
        - 10091
        - 10092
        - 35531
        - 39442
        - 46244
        - 57486
        - 63221
        - 116058
        - 180454
        - 377270
        - 377271
        - 377586
        - 377587
        - 943925
        - 943926

